name: Bug report
description: Create a new ticket for a bug.
title: "🐛 [BUG]: "
labels:
  - bug
  - triage
assignees:
  - TheGeeKing
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Minimal Reproduction
      description: Provide steps to reproduce the problem.
      value: |-
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Exception or Error
      description: provide error logs
  - type: textarea
    attributes:
      label: Screenshots/Screen recording
      description: If applicable, add screenshots/recording to help explain your problem.
      placeholder: Add screenshots/recording here
  - type: input
    attributes:
      label: Operating System and Version
      placeholder: eg. Windows 10, macOS 10.15, Ubuntu 20.04, etc.
    validations:
      required: true
  - type: input
    attributes:
      label: Python Version
      placeholder: e.g. 3.11
    validations:
      required: true
  - type: input
    attributes:
      label: Tautulli version
      description: Check Tautulli > Settings > Help & Info.
      placeholder: e.g. 2.12.5
    validations:
      required: true
  - type: input
    attributes:
      label: Plex Media Server Version
      description: Check Plex Server > Settings (not Plex Web) > General.
      placeholder: eg. 1.75.0.3920
    validations:
      required: true
